### ISSUE TITLE
Folders not displaying correctly

### ISSUE THREAD

**Issue by overdox** [ironmonk88/monks-enhanced-journal#33]
Folders appears to not stretch horizontally all the way to the sides within the bounding box on the pathfinder 1e system. 
Tested on pf1e 0.78.8 on FVTT 0.8.6 with no other modules enabled.
![Folders](https://user-images.githubusercontent.com/6378329/121550954-820ad400-ca0f-11eb-8509-1b45adc62f92.png)

**Comment by mkahvi** [comment]
Quick solution for the problem as mentioned in Discord:
```css
.monks-enhanced-journal .directory-list .directory-item header { width: 100%; }
```
